services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    ports:
      - 3306:3306
    networks:
      - spring-boot

  swaggerui:
    image: swaggerapi/swagger-ui
    container_name: swaggerui
    environment:
      - SWAGGER_JSON=/swagger.yml
    volumes:
      - ./swagger/swagger.yml:/swagger.yml
    ports:
      - 8081:8080
    networks:
      - spring-boot

  base:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    image: base:latest
    container_name: base
    networks:
      - spring-boot

  developer:
    build:
      context: .
      dockerfile: Dockerfile
      target: developer
      args:
        - USER=${USER}
        - UID=${UID}
        - GID=${GID}
    image: developer:latest
    container_name: developer
    env_file: .env
    volumes:
      - .:/home/${USER}/workspace
      - ~/.ssh:/home/${USER}/.ssh
      - ~/.zshrc:/home/${USER}/.zshrc
    depends_on:
      - base
    ports:
      - 8080:8080
    networks:
      - spring-boot

networks:
  spring-boot:
    driver: bridge